# Generated by Django 4.2.7 on 2026-08-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Duration in semesters')),
                ('session', models.CharField(choices=[('DAY', 'Day'), ('WEEKEND', 'Weekend'), ('EVENING', 'Evening')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='programmes__code_924b0e_idx'), models.Index(fields=['is_active'], name='programmes__is_acti_867457_idx')],
            },
        ),
    ]
