# Generated by Django 4.2.7 on 2026-08-30 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('programmes', '0001_initial'),
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lecture_type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('ONLINE', 'Online')], default='PHYSICAL', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('verification_code', models.CharField(blank=True, max_length=20)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_attempts', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicperiod')),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.courseunit')),
                ('lecturer', models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.PROTECT, related_name='lectures', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programmes.programme')),
            ],
            options={
                'ordering': ['-scheduled_date', '-start_time'],
                'indexes': [models.Index(fields=['course_unit', 'academic_period'], name='lectures_le_course__41d76a_idx'), models.Index(fields=['lecturer', 'scheduled_date'], name='lectures_le_lecture_4ec6d0_idx'), models.Index(fields=['status', 'scheduled_date'], name='lectures_le_status_f7fd4c_idx'), models.Index(fields=['verification_code'], name='lectures_le_verific_03b2e6_idx')],
            },
        ),
    ]
