# Generated by Django 4.2.7 on 2026-09-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='room_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude of the room for physical lectures', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='room_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude of the room for physical lectures', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='room_radius',
            field=models.IntegerField(default=50, help_text='Allowed radius in meters from the room coordinates'),
        ),
    ]
